// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emneymzatrvkqmjzasjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbmV5bXphdHJ2a3Ftanphc2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMTI1NzEsImV4cCI6MjA1NTY4ODU3MX0.ThVu85A3_L419pCY9t2-pylSTT7-6kve0aBktuC6XU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);